# Spring properties
server:
  port: 8080
  servlet:
    context-path : /rest-api-jpa

logging:
  level:
    br: DEBUG #TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    #com.zaxxer: DEBUG
    #$org.hibernate: DEBUG
    #o.hibernate: DEBUG

spring:
  application:
    name: exemplo-rest-api-jpa
  profiles:
    active: local
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true